server:
  port: ${DISCOVERY_SERVICE_PORT:8061}

eureka:
  instance:
    hostname: ${DISCOVERY_SERVICE_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/